# Add 'area: web' label to any changes within apps/web
'area: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

# Add 'area: admin' label to any changes within apps/admin
'area: admin':
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

# Add 'area: docs' label to any changes to documentation
'area: docs':
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

# Add 'area: ui' label to any changes within packages/ui
'area: ui':
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

# Add 'area: database' label to any changes within packages/database
'area: database':
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

# Add 'area: config' label to any changes within packages/config
'area: config':
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'

# Add 'area: env' label to any changes within packages/env
'area: env':
  - changed-files:
      - any-glob-to-any-file: 'packages/env/**/*'
