"area: web":
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

"area: admin":
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

"area: droid":
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

"area: packages":
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

"area: docs":
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

"area: ci":
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
