# .github/labeler.yml

# Area: Web
"area: web":
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

# Area: Admin
"area: admin":
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

# Area: Droid
"area: droid":
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

# Area: Packages
"area: packages":
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

# Area: CI/CD
"area: ci":
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

# Area: Documentation
"area: docs":
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
