'area: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

'area: admin':
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

'area: droid':
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

'area: ui':
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

'area: database':
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

'area: env':
  - changed-files:
      - any-glob-to-any-file: 'packages/env/**/*'

'area: config':
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'

'area: utils':
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/**/*'

area: ops:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'package.json'
