# This is a configuration file for the `actions/labeler` action.
# It allows you to automatically label pull requests based on the files that are modified.

# Area: Web
web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

# Area: Admin
admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

# Area: Droid
droid:
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

# Area: Payment Engine
payment-engine:
  - changed-files:
      - any-glob-to-any-file: 'packages/payment-engine/**/*'

# Area: UI
ui:
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

# Area: Database
database:
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

# Area: Env
env:
  - changed-files:
      - any-glob-to-any-file: 'packages/env/**/*'

# Area: Utils
utils:
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/**/*'

# Area: Config
config:
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'

# Area: Documentation
docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

# Type: CI/CD
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

# Type: Config
configuration:
  - changed-files:
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'pnpm-workspace.yaml'
      - any-glob-to-any-file: '.npmrc'
      - any-glob-to-any-file: 'tsconfig.json'
      - any-glob-to-any-file: 'biome.json'
