# Area Labels
area-web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

area-admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

area-droid:
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

area-core:
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

area-ops:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'package.json'

# Type Labels
type-feat:
  - head-branch: ['feat/*', 'feature/*']

type-fix:
  - head-branch: ['fix/*', 'hotfix/*']

type-chore:
  - head-branch: ['chore/*']

type-docs:
  - head-branch: ['docs/*']

type-test:
  - head-branch: ['test/*']

type-refactor:
  - head-branch: ['refactor/*']

type-ci:
  - head-branch: ['ci/*']
