area_web:
  - changed-files:
    - any-glob-to-any-file: 'apps/web/**/*'

area_admin:
  - changed-files:
    - any-glob-to-any-file: 'apps/admin/**/*'

area_droid:
  - changed-files:
    - any-glob-to-any-file: 'apps/droid/**/*'

area_core:
  - changed-files:
    - any-glob-to-any-file: 'packages/**/*'

area_ops:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
    - any-glob-to-any-file: 'turbo.json'
    - any-glob-to-any-file: 'package.json'
