web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

droid:
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

core:
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

ops:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'package.json'
