area: web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

area: admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

area: droid:
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

area: ui:
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

area: config:
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'

area: utils:
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/**/*'

area: database:
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

area: env:
  - changed-files:
      - any-glob-to-any-file: 'packages/env/**/*'
